version: "3.2"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    command: npx nodemon www.js
    env_file:
      - .env
    ports:
      - "8080:8080" #out:in
    links:
      - db:db
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules #

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    restart: always
    ports:
      - "80:80"
    environment:
      containerName: app
      containerPort: 3030
    #logging:
    #  driver: "none" #disable nginx logs
    links:
      - app:app
    depends_on:
      - app

  db:
    image: postgres:12.2-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432" #out:in

volumes:
  node_modules:
